// Copyright 2020 Alibekov Murad
#ifndef MODULES_TASK_2_ALIBEKOV_M_SEIDEL_METHOD_SEIDEL_METHOD_H_
#define MODULES_TASK_2_ALIBEKOV_M_SEIDEL_METHOD_SEIDEL_METHOD_H_

inline int idx(int i, int j, int N) { return i * N + j; }

#endif  // MODULES_TASK_2_ALIBEKOV_M_SEIDEL_METHOD_SEIDEL_METHOD_H_
